// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bitcoinserver.proto

package com.BitcoinServer;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface BroadcastPaymentOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .payments.PaymentRequest payment_request = 1;
    /**
     * <code>optional .payments.PaymentRequest payment_request = 1;</code>
     */
    boolean hasPaymentRequest();
    /**
     * <code>optional .payments.PaymentRequest payment_request = 1;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentRequest getPaymentRequest();
    /**
     * <code>optional .payments.PaymentRequest payment_request = 1;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentRequestOrBuilder getPaymentRequestOrBuilder();

    // optional .payments.Payment payment = 2;
    /**
     * <code>optional .payments.Payment payment = 2;</code>
     */
    boolean hasPayment();
    /**
     * <code>optional .payments.Payment payment = 2;</code>
     */
    org.bitcoin.protocols.payments.Protos.Payment getPayment();
    /**
     * <code>optional .payments.Payment payment = 2;</code>
     */
    org.bitcoin.protocols.payments.Protos.PaymentOrBuilder getPaymentOrBuilder();
  }
  /**
   * Protobuf type {@code BitcoinServer.BroadcastPayment}
   */
  public static final class BroadcastPayment extends
      com.google.protobuf.GeneratedMessage
      implements BroadcastPaymentOrBuilder {
    // Use BroadcastPayment.newBuilder() to construct.
    private BroadcastPayment(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BroadcastPayment(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BroadcastPayment defaultInstance;
    public static BroadcastPayment getDefaultInstance() {
      return defaultInstance;
    }

    public BroadcastPayment getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BroadcastPayment(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              org.bitcoin.protocols.payments.Protos.PaymentRequest.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = paymentRequest_.toBuilder();
              }
              paymentRequest_ = input.readMessage(org.bitcoin.protocols.payments.Protos.PaymentRequest.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(paymentRequest_);
                paymentRequest_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              org.bitcoin.protocols.payments.Protos.Payment.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = payment_.toBuilder();
              }
              payment_ = input.readMessage(org.bitcoin.protocols.payments.Protos.Payment.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(payment_);
                payment_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastPayment_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastPayment_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.BitcoinServer.Protos.BroadcastPayment.class, com.BitcoinServer.Protos.BroadcastPayment.Builder.class);
    }

    public static com.google.protobuf.Parser<BroadcastPayment> PARSER =
        new com.google.protobuf.AbstractParser<BroadcastPayment>() {
      public BroadcastPayment parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BroadcastPayment(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BroadcastPayment> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional .payments.PaymentRequest payment_request = 1;
    public static final int PAYMENT_REQUEST_FIELD_NUMBER = 1;
    private org.bitcoin.protocols.payments.Protos.PaymentRequest paymentRequest_;
    /**
     * <code>optional .payments.PaymentRequest payment_request = 1;</code>
     */
    public boolean hasPaymentRequest() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .payments.PaymentRequest payment_request = 1;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentRequest getPaymentRequest() {
      return paymentRequest_;
    }
    /**
     * <code>optional .payments.PaymentRequest payment_request = 1;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentRequestOrBuilder getPaymentRequestOrBuilder() {
      return paymentRequest_;
    }

    // optional .payments.Payment payment = 2;
    public static final int PAYMENT_FIELD_NUMBER = 2;
    private org.bitcoin.protocols.payments.Protos.Payment payment_;
    /**
     * <code>optional .payments.Payment payment = 2;</code>
     */
    public boolean hasPayment() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .payments.Payment payment = 2;</code>
     */
    public org.bitcoin.protocols.payments.Protos.Payment getPayment() {
      return payment_;
    }
    /**
     * <code>optional .payments.Payment payment = 2;</code>
     */
    public org.bitcoin.protocols.payments.Protos.PaymentOrBuilder getPaymentOrBuilder() {
      return payment_;
    }

    private void initFields() {
      paymentRequest_ = org.bitcoin.protocols.payments.Protos.PaymentRequest.getDefaultInstance();
      payment_ = org.bitcoin.protocols.payments.Protos.Payment.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasPaymentRequest()) {
        if (!getPaymentRequest().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasPayment()) {
        if (!getPayment().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, paymentRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, payment_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, paymentRequest_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, payment_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.BitcoinServer.Protos.BroadcastPayment parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.BitcoinServer.Protos.BroadcastPayment parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastPayment parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.BitcoinServer.Protos.BroadcastPayment parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastPayment parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.BitcoinServer.Protos.BroadcastPayment parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastPayment parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.BitcoinServer.Protos.BroadcastPayment parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastPayment parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.BitcoinServer.Protos.BroadcastPayment parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.BitcoinServer.Protos.BroadcastPayment prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BitcoinServer.BroadcastPayment}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.BitcoinServer.Protos.BroadcastPaymentOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastPayment_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastPayment_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.BitcoinServer.Protos.BroadcastPayment.class, com.BitcoinServer.Protos.BroadcastPayment.Builder.class);
      }

      // Construct using com.BitcoinServer.Protos.BroadcastPayment.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPaymentRequestFieldBuilder();
          getPaymentFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (paymentRequestBuilder_ == null) {
          paymentRequest_ = org.bitcoin.protocols.payments.Protos.PaymentRequest.getDefaultInstance();
        } else {
          paymentRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (paymentBuilder_ == null) {
          payment_ = org.bitcoin.protocols.payments.Protos.Payment.getDefaultInstance();
        } else {
          paymentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastPayment_descriptor;
      }

      public com.BitcoinServer.Protos.BroadcastPayment getDefaultInstanceForType() {
        return com.BitcoinServer.Protos.BroadcastPayment.getDefaultInstance();
      }

      public com.BitcoinServer.Protos.BroadcastPayment build() {
        com.BitcoinServer.Protos.BroadcastPayment result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.BitcoinServer.Protos.BroadcastPayment buildPartial() {
        com.BitcoinServer.Protos.BroadcastPayment result = new com.BitcoinServer.Protos.BroadcastPayment(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (paymentRequestBuilder_ == null) {
          result.paymentRequest_ = paymentRequest_;
        } else {
          result.paymentRequest_ = paymentRequestBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (paymentBuilder_ == null) {
          result.payment_ = payment_;
        } else {
          result.payment_ = paymentBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.BitcoinServer.Protos.BroadcastPayment) {
          return mergeFrom((com.BitcoinServer.Protos.BroadcastPayment)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.BitcoinServer.Protos.BroadcastPayment other) {
        if (other == com.BitcoinServer.Protos.BroadcastPayment.getDefaultInstance()) return this;
        if (other.hasPaymentRequest()) {
          mergePaymentRequest(other.getPaymentRequest());
        }
        if (other.hasPayment()) {
          mergePayment(other.getPayment());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasPaymentRequest()) {
          if (!getPaymentRequest().isInitialized()) {
            
            return false;
          }
        }
        if (hasPayment()) {
          if (!getPayment().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.BitcoinServer.Protos.BroadcastPayment parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.BitcoinServer.Protos.BroadcastPayment) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .payments.PaymentRequest payment_request = 1;
      private org.bitcoin.protocols.payments.Protos.PaymentRequest paymentRequest_ = org.bitcoin.protocols.payments.Protos.PaymentRequest.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoin.protocols.payments.Protos.PaymentRequest, org.bitcoin.protocols.payments.Protos.PaymentRequest.Builder, org.bitcoin.protocols.payments.Protos.PaymentRequestOrBuilder> paymentRequestBuilder_;
      /**
       * <code>optional .payments.PaymentRequest payment_request = 1;</code>
       */
      public boolean hasPaymentRequest() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .payments.PaymentRequest payment_request = 1;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentRequest getPaymentRequest() {
        if (paymentRequestBuilder_ == null) {
          return paymentRequest_;
        } else {
          return paymentRequestBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .payments.PaymentRequest payment_request = 1;</code>
       */
      public Builder setPaymentRequest(org.bitcoin.protocols.payments.Protos.PaymentRequest value) {
        if (paymentRequestBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          paymentRequest_ = value;
          onChanged();
        } else {
          paymentRequestBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .payments.PaymentRequest payment_request = 1;</code>
       */
      public Builder setPaymentRequest(
          org.bitcoin.protocols.payments.Protos.PaymentRequest.Builder builderForValue) {
        if (paymentRequestBuilder_ == null) {
          paymentRequest_ = builderForValue.build();
          onChanged();
        } else {
          paymentRequestBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .payments.PaymentRequest payment_request = 1;</code>
       */
      public Builder mergePaymentRequest(org.bitcoin.protocols.payments.Protos.PaymentRequest value) {
        if (paymentRequestBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              paymentRequest_ != org.bitcoin.protocols.payments.Protos.PaymentRequest.getDefaultInstance()) {
            paymentRequest_ =
              org.bitcoin.protocols.payments.Protos.PaymentRequest.newBuilder(paymentRequest_).mergeFrom(value).buildPartial();
          } else {
            paymentRequest_ = value;
          }
          onChanged();
        } else {
          paymentRequestBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .payments.PaymentRequest payment_request = 1;</code>
       */
      public Builder clearPaymentRequest() {
        if (paymentRequestBuilder_ == null) {
          paymentRequest_ = org.bitcoin.protocols.payments.Protos.PaymentRequest.getDefaultInstance();
          onChanged();
        } else {
          paymentRequestBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .payments.PaymentRequest payment_request = 1;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentRequest.Builder getPaymentRequestBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getPaymentRequestFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .payments.PaymentRequest payment_request = 1;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentRequestOrBuilder getPaymentRequestOrBuilder() {
        if (paymentRequestBuilder_ != null) {
          return paymentRequestBuilder_.getMessageOrBuilder();
        } else {
          return paymentRequest_;
        }
      }
      /**
       * <code>optional .payments.PaymentRequest payment_request = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoin.protocols.payments.Protos.PaymentRequest, org.bitcoin.protocols.payments.Protos.PaymentRequest.Builder, org.bitcoin.protocols.payments.Protos.PaymentRequestOrBuilder> 
          getPaymentRequestFieldBuilder() {
        if (paymentRequestBuilder_ == null) {
          paymentRequestBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bitcoin.protocols.payments.Protos.PaymentRequest, org.bitcoin.protocols.payments.Protos.PaymentRequest.Builder, org.bitcoin.protocols.payments.Protos.PaymentRequestOrBuilder>(
                  paymentRequest_,
                  getParentForChildren(),
                  isClean());
          paymentRequest_ = null;
        }
        return paymentRequestBuilder_;
      }

      // optional .payments.Payment payment = 2;
      private org.bitcoin.protocols.payments.Protos.Payment payment_ = org.bitcoin.protocols.payments.Protos.Payment.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoin.protocols.payments.Protos.Payment, org.bitcoin.protocols.payments.Protos.Payment.Builder, org.bitcoin.protocols.payments.Protos.PaymentOrBuilder> paymentBuilder_;
      /**
       * <code>optional .payments.Payment payment = 2;</code>
       */
      public boolean hasPayment() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .payments.Payment payment = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.Payment getPayment() {
        if (paymentBuilder_ == null) {
          return payment_;
        } else {
          return paymentBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .payments.Payment payment = 2;</code>
       */
      public Builder setPayment(org.bitcoin.protocols.payments.Protos.Payment value) {
        if (paymentBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          payment_ = value;
          onChanged();
        } else {
          paymentBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .payments.Payment payment = 2;</code>
       */
      public Builder setPayment(
          org.bitcoin.protocols.payments.Protos.Payment.Builder builderForValue) {
        if (paymentBuilder_ == null) {
          payment_ = builderForValue.build();
          onChanged();
        } else {
          paymentBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .payments.Payment payment = 2;</code>
       */
      public Builder mergePayment(org.bitcoin.protocols.payments.Protos.Payment value) {
        if (paymentBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              payment_ != org.bitcoin.protocols.payments.Protos.Payment.getDefaultInstance()) {
            payment_ =
              org.bitcoin.protocols.payments.Protos.Payment.newBuilder(payment_).mergeFrom(value).buildPartial();
          } else {
            payment_ = value;
          }
          onChanged();
        } else {
          paymentBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .payments.Payment payment = 2;</code>
       */
      public Builder clearPayment() {
        if (paymentBuilder_ == null) {
          payment_ = org.bitcoin.protocols.payments.Protos.Payment.getDefaultInstance();
          onChanged();
        } else {
          paymentBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .payments.Payment payment = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.Payment.Builder getPaymentBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getPaymentFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .payments.Payment payment = 2;</code>
       */
      public org.bitcoin.protocols.payments.Protos.PaymentOrBuilder getPaymentOrBuilder() {
        if (paymentBuilder_ != null) {
          return paymentBuilder_.getMessageOrBuilder();
        } else {
          return payment_;
        }
      }
      /**
       * <code>optional .payments.Payment payment = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          org.bitcoin.protocols.payments.Protos.Payment, org.bitcoin.protocols.payments.Protos.Payment.Builder, org.bitcoin.protocols.payments.Protos.PaymentOrBuilder> 
          getPaymentFieldBuilder() {
        if (paymentBuilder_ == null) {
          paymentBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.bitcoin.protocols.payments.Protos.Payment, org.bitcoin.protocols.payments.Protos.Payment.Builder, org.bitcoin.protocols.payments.Protos.PaymentOrBuilder>(
                  payment_,
                  getParentForChildren(),
                  isClean());
          payment_ = null;
        }
        return paymentBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:BitcoinServer.BroadcastPayment)
    }

    static {
      defaultInstance = new BroadcastPayment(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BitcoinServer.BroadcastPayment)
  }

  public interface BroadcastPaymentResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string error = 1;
    /**
     * <code>optional string error = 1;</code>
     */
    boolean hasError();
    /**
     * <code>optional string error = 1;</code>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 1;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code BitcoinServer.BroadcastPaymentResponse}
   */
  public static final class BroadcastPaymentResponse extends
      com.google.protobuf.GeneratedMessage
      implements BroadcastPaymentResponseOrBuilder {
    // Use BroadcastPaymentResponse.newBuilder() to construct.
    private BroadcastPaymentResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BroadcastPaymentResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BroadcastPaymentResponse defaultInstance;
    public static BroadcastPaymentResponse getDefaultInstance() {
      return defaultInstance;
    }

    public BroadcastPaymentResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BroadcastPaymentResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              error_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastPaymentResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastPaymentResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.BitcoinServer.Protos.BroadcastPaymentResponse.class, com.BitcoinServer.Protos.BroadcastPaymentResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<BroadcastPaymentResponse> PARSER =
        new com.google.protobuf.AbstractParser<BroadcastPaymentResponse>() {
      public BroadcastPaymentResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BroadcastPaymentResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BroadcastPaymentResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 1;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string error = 1;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 1;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      error_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getErrorBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getErrorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.BitcoinServer.Protos.BroadcastPaymentResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.BitcoinServer.Protos.BroadcastPaymentResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastPaymentResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.BitcoinServer.Protos.BroadcastPaymentResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastPaymentResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.BitcoinServer.Protos.BroadcastPaymentResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastPaymentResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.BitcoinServer.Protos.BroadcastPaymentResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastPaymentResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.BitcoinServer.Protos.BroadcastPaymentResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.BitcoinServer.Protos.BroadcastPaymentResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BitcoinServer.BroadcastPaymentResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.BitcoinServer.Protos.BroadcastPaymentResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastPaymentResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastPaymentResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.BitcoinServer.Protos.BroadcastPaymentResponse.class, com.BitcoinServer.Protos.BroadcastPaymentResponse.Builder.class);
      }

      // Construct using com.BitcoinServer.Protos.BroadcastPaymentResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastPaymentResponse_descriptor;
      }

      public com.BitcoinServer.Protos.BroadcastPaymentResponse getDefaultInstanceForType() {
        return com.BitcoinServer.Protos.BroadcastPaymentResponse.getDefaultInstance();
      }

      public com.BitcoinServer.Protos.BroadcastPaymentResponse build() {
        com.BitcoinServer.Protos.BroadcastPaymentResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.BitcoinServer.Protos.BroadcastPaymentResponse buildPartial() {
        com.BitcoinServer.Protos.BroadcastPaymentResponse result = new com.BitcoinServer.Protos.BroadcastPaymentResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.BitcoinServer.Protos.BroadcastPaymentResponse) {
          return mergeFrom((com.BitcoinServer.Protos.BroadcastPaymentResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.BitcoinServer.Protos.BroadcastPaymentResponse other) {
        if (other == com.BitcoinServer.Protos.BroadcastPaymentResponse.getDefaultInstance()) return this;
        if (other.hasError()) {
          bitField0_ |= 0x00000001;
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.BitcoinServer.Protos.BroadcastPaymentResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.BitcoinServer.Protos.BroadcastPaymentResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string error = 1;
      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 1;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string error = 1;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 1;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 1;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 1;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 1;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BitcoinServer.BroadcastPaymentResponse)
    }

    static {
      defaultInstance = new BroadcastPaymentResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BitcoinServer.BroadcastPaymentResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BitcoinServer_BroadcastPayment_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BitcoinServer_BroadcastPayment_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BitcoinServer_BroadcastPaymentResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BitcoinServer_BroadcastPaymentResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023bitcoinserver.proto\022\rBitcoinServer\032\024pa" +
      "ymentrequest.proto\"i\n\020BroadcastPayment\0221" +
      "\n\017payment_request\030\001 \001(\0132\030.payments.Payme" +
      "ntRequest\022\"\n\007payment\030\002 \001(\0132\021.payments.Pa" +
      "yment\")\n\030BroadcastPaymentResponse\022\r\n\005err" +
      "or\030\001 \001(\tB\033\n\021com.BitcoinServerB\006Protos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BitcoinServer_BroadcastPayment_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BitcoinServer_BroadcastPayment_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BitcoinServer_BroadcastPayment_descriptor,
              new java.lang.String[] { "PaymentRequest", "Payment", });
          internal_static_BitcoinServer_BroadcastPaymentResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_BitcoinServer_BroadcastPaymentResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BitcoinServer_BroadcastPaymentResponse_descriptor,
              new java.lang.String[] { "Error", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          org.bitcoin.protocols.payments.Protos.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
