// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: bitcoinserver.proto

package com.BitcoinServer;

public final class Protos {
  private Protos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface TransactionListOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string network = 1 [default = "main"];
    /**
     * <code>optional string network = 1 [default = "main"];</code>
     *
     * <pre>
     * "main" or "test"
     * </pre>
     */
    boolean hasNetwork();
    /**
     * <code>optional string network = 1 [default = "main"];</code>
     *
     * <pre>
     * "main" or "test"
     * </pre>
     */
    java.lang.String getNetwork();
    /**
     * <code>optional string network = 1 [default = "main"];</code>
     *
     * <pre>
     * "main" or "test"
     * </pre>
     */
    com.google.protobuf.ByteString
        getNetworkBytes();

    // repeated bytes transactions = 2;
    /**
     * <code>repeated bytes transactions = 2;</code>
     *
     * <pre>
     * List of transactions
     * </pre>
     */
    java.util.List<com.google.protobuf.ByteString> getTransactionsList();
    /**
     * <code>repeated bytes transactions = 2;</code>
     *
     * <pre>
     * List of transactions
     * </pre>
     */
    int getTransactionsCount();
    /**
     * <code>repeated bytes transactions = 2;</code>
     *
     * <pre>
     * List of transactions
     * </pre>
     */
    com.google.protobuf.ByteString getTransactions(int index);
  }
  /**
   * Protobuf type {@code BitcoinServer.TransactionList}
   */
  public static final class TransactionList extends
      com.google.protobuf.GeneratedMessage
      implements TransactionListOrBuilder {
    // Use TransactionList.newBuilder() to construct.
    private TransactionList(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private TransactionList(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final TransactionList defaultInstance;
    public static TransactionList getDefaultInstance() {
      return defaultInstance;
    }

    public TransactionList getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private TransactionList(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              network_ = input.readBytes();
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
                transactions_ = new java.util.ArrayList<com.google.protobuf.ByteString>();
                mutable_bitField0_ |= 0x00000002;
              }
              transactions_.add(input.readBytes());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) == 0x00000002)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.BitcoinServer.Protos.internal_static_BitcoinServer_TransactionList_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.BitcoinServer.Protos.internal_static_BitcoinServer_TransactionList_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.BitcoinServer.Protos.TransactionList.class, com.BitcoinServer.Protos.TransactionList.Builder.class);
    }

    public static com.google.protobuf.Parser<TransactionList> PARSER =
        new com.google.protobuf.AbstractParser<TransactionList>() {
      public TransactionList parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TransactionList(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<TransactionList> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string network = 1 [default = "main"];
    public static final int NETWORK_FIELD_NUMBER = 1;
    private java.lang.Object network_;
    /**
     * <code>optional string network = 1 [default = "main"];</code>
     *
     * <pre>
     * "main" or "test"
     * </pre>
     */
    public boolean hasNetwork() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string network = 1 [default = "main"];</code>
     *
     * <pre>
     * "main" or "test"
     * </pre>
     */
    public java.lang.String getNetwork() {
      java.lang.Object ref = network_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          network_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string network = 1 [default = "main"];</code>
     *
     * <pre>
     * "main" or "test"
     * </pre>
     */
    public com.google.protobuf.ByteString
        getNetworkBytes() {
      java.lang.Object ref = network_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        network_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // repeated bytes transactions = 2;
    public static final int TRANSACTIONS_FIELD_NUMBER = 2;
    private java.util.List<com.google.protobuf.ByteString> transactions_;
    /**
     * <code>repeated bytes transactions = 2;</code>
     *
     * <pre>
     * List of transactions
     * </pre>
     */
    public java.util.List<com.google.protobuf.ByteString>
        getTransactionsList() {
      return transactions_;
    }
    /**
     * <code>repeated bytes transactions = 2;</code>
     *
     * <pre>
     * List of transactions
     * </pre>
     */
    public int getTransactionsCount() {
      return transactions_.size();
    }
    /**
     * <code>repeated bytes transactions = 2;</code>
     *
     * <pre>
     * List of transactions
     * </pre>
     */
    public com.google.protobuf.ByteString getTransactions(int index) {
      return transactions_.get(index);
    }

    private void initFields() {
      network_ = "main";
      transactions_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNetworkBytes());
      }
      for (int i = 0; i < transactions_.size(); i++) {
        output.writeBytes(2, transactions_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNetworkBytes());
      }
      {
        int dataSize = 0;
        for (int i = 0; i < transactions_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(transactions_.get(i));
        }
        size += dataSize;
        size += 1 * getTransactionsList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.BitcoinServer.Protos.TransactionList parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.BitcoinServer.Protos.TransactionList parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.TransactionList parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.BitcoinServer.Protos.TransactionList parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.TransactionList parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.BitcoinServer.Protos.TransactionList parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.TransactionList parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.BitcoinServer.Protos.TransactionList parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.TransactionList parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.BitcoinServer.Protos.TransactionList parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.BitcoinServer.Protos.TransactionList prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BitcoinServer.TransactionList}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.BitcoinServer.Protos.TransactionListOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_TransactionList_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_TransactionList_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.BitcoinServer.Protos.TransactionList.class, com.BitcoinServer.Protos.TransactionList.Builder.class);
      }

      // Construct using com.BitcoinServer.Protos.TransactionList.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        network_ = "main";
        bitField0_ = (bitField0_ & ~0x00000001);
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_TransactionList_descriptor;
      }

      public com.BitcoinServer.Protos.TransactionList getDefaultInstanceForType() {
        return com.BitcoinServer.Protos.TransactionList.getDefaultInstance();
      }

      public com.BitcoinServer.Protos.TransactionList build() {
        com.BitcoinServer.Protos.TransactionList result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.BitcoinServer.Protos.TransactionList buildPartial() {
        com.BitcoinServer.Protos.TransactionList result = new com.BitcoinServer.Protos.TransactionList(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.network_ = network_;
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          transactions_ = java.util.Collections.unmodifiableList(transactions_);
          bitField0_ = (bitField0_ & ~0x00000002);
        }
        result.transactions_ = transactions_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.BitcoinServer.Protos.TransactionList) {
          return mergeFrom((com.BitcoinServer.Protos.TransactionList)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.BitcoinServer.Protos.TransactionList other) {
        if (other == com.BitcoinServer.Protos.TransactionList.getDefaultInstance()) return this;
        if (other.hasNetwork()) {
          bitField0_ |= 0x00000001;
          network_ = other.network_;
          onChanged();
        }
        if (!other.transactions_.isEmpty()) {
          if (transactions_.isEmpty()) {
            transactions_ = other.transactions_;
            bitField0_ = (bitField0_ & ~0x00000002);
          } else {
            ensureTransactionsIsMutable();
            transactions_.addAll(other.transactions_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.BitcoinServer.Protos.TransactionList parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.BitcoinServer.Protos.TransactionList) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string network = 1 [default = "main"];
      private java.lang.Object network_ = "main";
      /**
       * <code>optional string network = 1 [default = "main"];</code>
       *
       * <pre>
       * "main" or "test"
       * </pre>
       */
      public boolean hasNetwork() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string network = 1 [default = "main"];</code>
       *
       * <pre>
       * "main" or "test"
       * </pre>
       */
      public java.lang.String getNetwork() {
        java.lang.Object ref = network_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          network_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string network = 1 [default = "main"];</code>
       *
       * <pre>
       * "main" or "test"
       * </pre>
       */
      public com.google.protobuf.ByteString
          getNetworkBytes() {
        java.lang.Object ref = network_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          network_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string network = 1 [default = "main"];</code>
       *
       * <pre>
       * "main" or "test"
       * </pre>
       */
      public Builder setNetwork(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        network_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string network = 1 [default = "main"];</code>
       *
       * <pre>
       * "main" or "test"
       * </pre>
       */
      public Builder clearNetwork() {
        bitField0_ = (bitField0_ & ~0x00000001);
        network_ = getDefaultInstance().getNetwork();
        onChanged();
        return this;
      }
      /**
       * <code>optional string network = 1 [default = "main"];</code>
       *
       * <pre>
       * "main" or "test"
       * </pre>
       */
      public Builder setNetworkBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        network_ = value;
        onChanged();
        return this;
      }

      // repeated bytes transactions = 2;
      private java.util.List<com.google.protobuf.ByteString> transactions_ = java.util.Collections.emptyList();
      private void ensureTransactionsIsMutable() {
        if (!((bitField0_ & 0x00000002) == 0x00000002)) {
          transactions_ = new java.util.ArrayList<com.google.protobuf.ByteString>(transactions_);
          bitField0_ |= 0x00000002;
         }
      }
      /**
       * <code>repeated bytes transactions = 2;</code>
       *
       * <pre>
       * List of transactions
       * </pre>
       */
      public java.util.List<com.google.protobuf.ByteString>
          getTransactionsList() {
        return java.util.Collections.unmodifiableList(transactions_);
      }
      /**
       * <code>repeated bytes transactions = 2;</code>
       *
       * <pre>
       * List of transactions
       * </pre>
       */
      public int getTransactionsCount() {
        return transactions_.size();
      }
      /**
       * <code>repeated bytes transactions = 2;</code>
       *
       * <pre>
       * List of transactions
       * </pre>
       */
      public com.google.protobuf.ByteString getTransactions(int index) {
        return transactions_.get(index);
      }
      /**
       * <code>repeated bytes transactions = 2;</code>
       *
       * <pre>
       * List of transactions
       * </pre>
       */
      public Builder setTransactions(
          int index, com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionsIsMutable();
        transactions_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transactions = 2;</code>
       *
       * <pre>
       * List of transactions
       * </pre>
       */
      public Builder addTransactions(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureTransactionsIsMutable();
        transactions_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transactions = 2;</code>
       *
       * <pre>
       * List of transactions
       * </pre>
       */
      public Builder addAllTransactions(
          java.lang.Iterable<? extends com.google.protobuf.ByteString> values) {
        ensureTransactionsIsMutable();
        super.addAll(values, transactions_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated bytes transactions = 2;</code>
       *
       * <pre>
       * List of transactions
       * </pre>
       */
      public Builder clearTransactions() {
        transactions_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BitcoinServer.TransactionList)
    }

    static {
      defaultInstance = new TransactionList(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BitcoinServer.TransactionList)
  }

  public interface BroadcastResponseOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional string error = 1;
    /**
     * <code>optional string error = 1;</code>
     */
    boolean hasError();
    /**
     * <code>optional string error = 1;</code>
     */
    java.lang.String getError();
    /**
     * <code>optional string error = 1;</code>
     */
    com.google.protobuf.ByteString
        getErrorBytes();
  }
  /**
   * Protobuf type {@code BitcoinServer.BroadcastResponse}
   */
  public static final class BroadcastResponse extends
      com.google.protobuf.GeneratedMessage
      implements BroadcastResponseOrBuilder {
    // Use BroadcastResponse.newBuilder() to construct.
    private BroadcastResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private BroadcastResponse(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final BroadcastResponse defaultInstance;
    public static BroadcastResponse getDefaultInstance() {
      return defaultInstance;
    }

    public BroadcastResponse getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private BroadcastResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              error_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastResponse_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.BitcoinServer.Protos.BroadcastResponse.class, com.BitcoinServer.Protos.BroadcastResponse.Builder.class);
    }

    public static com.google.protobuf.Parser<BroadcastResponse> PARSER =
        new com.google.protobuf.AbstractParser<BroadcastResponse>() {
      public BroadcastResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BroadcastResponse(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<BroadcastResponse> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // optional string error = 1;
    public static final int ERROR_FIELD_NUMBER = 1;
    private java.lang.Object error_;
    /**
     * <code>optional string error = 1;</code>
     */
    public boolean hasError() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional string error = 1;</code>
     */
    public java.lang.String getError() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          error_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string error = 1;</code>
     */
    public com.google.protobuf.ByteString
        getErrorBytes() {
      java.lang.Object ref = error_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        error_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      error_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getErrorBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getErrorBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.BitcoinServer.Protos.BroadcastResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.BitcoinServer.Protos.BroadcastResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.BitcoinServer.Protos.BroadcastResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.BitcoinServer.Protos.BroadcastResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.BitcoinServer.Protos.BroadcastResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.BitcoinServer.Protos.BroadcastResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.BitcoinServer.Protos.BroadcastResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.BitcoinServer.Protos.BroadcastResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BitcoinServer.BroadcastResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements com.BitcoinServer.Protos.BroadcastResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastResponse_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.BitcoinServer.Protos.BroadcastResponse.class, com.BitcoinServer.Protos.BroadcastResponse.Builder.class);
      }

      // Construct using com.BitcoinServer.Protos.BroadcastResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        error_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.BitcoinServer.Protos.internal_static_BitcoinServer_BroadcastResponse_descriptor;
      }

      public com.BitcoinServer.Protos.BroadcastResponse getDefaultInstanceForType() {
        return com.BitcoinServer.Protos.BroadcastResponse.getDefaultInstance();
      }

      public com.BitcoinServer.Protos.BroadcastResponse build() {
        com.BitcoinServer.Protos.BroadcastResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.BitcoinServer.Protos.BroadcastResponse buildPartial() {
        com.BitcoinServer.Protos.BroadcastResponse result = new com.BitcoinServer.Protos.BroadcastResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.error_ = error_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.BitcoinServer.Protos.BroadcastResponse) {
          return mergeFrom((com.BitcoinServer.Protos.BroadcastResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.BitcoinServer.Protos.BroadcastResponse other) {
        if (other == com.BitcoinServer.Protos.BroadcastResponse.getDefaultInstance()) return this;
        if (other.hasError()) {
          bitField0_ |= 0x00000001;
          error_ = other.error_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.BitcoinServer.Protos.BroadcastResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.BitcoinServer.Protos.BroadcastResponse) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional string error = 1;
      private java.lang.Object error_ = "";
      /**
       * <code>optional string error = 1;</code>
       */
      public boolean hasError() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string error = 1;</code>
       */
      public java.lang.String getError() {
        java.lang.Object ref = error_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          error_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string error = 1;</code>
       */
      public com.google.protobuf.ByteString
          getErrorBytes() {
        java.lang.Object ref = error_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          error_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string error = 1;</code>
       */
      public Builder setError(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 1;</code>
       */
      public Builder clearError() {
        bitField0_ = (bitField0_ & ~0x00000001);
        error_ = getDefaultInstance().getError();
        onChanged();
        return this;
      }
      /**
       * <code>optional string error = 1;</code>
       */
      public Builder setErrorBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        error_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:BitcoinServer.BroadcastResponse)
    }

    static {
      defaultInstance = new BroadcastResponse(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:BitcoinServer.BroadcastResponse)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BitcoinServer_TransactionList_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BitcoinServer_TransactionList_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_BitcoinServer_BroadcastResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_BitcoinServer_BroadcastResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023bitcoinserver.proto\022\rBitcoinServer\">\n\017" +
      "TransactionList\022\025\n\007network\030\001 \001(\t:\004main\022\024" +
      "\n\014transactions\030\002 \003(\014\"\"\n\021BroadcastRespons" +
      "e\022\r\n\005error\030\001 \001(\tB\033\n\021com.BitcoinServerB\006P" +
      "rotos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_BitcoinServer_TransactionList_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_BitcoinServer_TransactionList_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BitcoinServer_TransactionList_descriptor,
              new java.lang.String[] { "Network", "Transactions", });
          internal_static_BitcoinServer_BroadcastResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_BitcoinServer_BroadcastResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_BitcoinServer_BroadcastResponse_descriptor,
              new java.lang.String[] { "Error", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
